In [6]:
from google.colab import files
uploaded = files.upload()

Saving max.csv to max.csv


In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
data2 = pd.read_csv("max.csv")
data2.head(20)

Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4  \
0                        NaN        Jan        Feb        Mar        Apr   
1                     Punjab        105         96       87.5      113.2   
2                Royal Seema       79.5         81       86.9       93.5   
3            Jammu & Kashmir      367.8      403.5      341.4      232.2   
4         Saurashtra & Kutch       12.5         21       46.2       64.4   
5             South Karnatak       24.4       44.3      108.9      127.7   
6                 Tamil Nadu      141.2      131.3      164.7      132.1   
7                  Telangana       98.7       79.1      108.6      105.6   
8                Uttarakhand      173.1      188.3      187.3      132.9   
9                   Vidharba       74.9       84.9       66.3      112.7   
10               West Bengal         60      112.8      152.5      174.2   
11                   West MP       54.1       40.5       53.5       13.7   
12            West Rajasthan       21.4       34.9         59       36.1   
13                   West Up       68.6       89.9       66.8       59.8   
14         Andaman & Nicobar      276.9      173.8      272.8      323.1   
15         Arunachal Pradesh      164.5      208.5      605.6      595.1   
16         Assam & Megahlaya       83.9       96.9      253.8      389.3   
17            Naga Mizo Mani       91.4      306.3      272.7      383.8   
18  SUB Himalaya WB & Sikkim        103      109.9      132.1       28.1   
19                    Orissa       70.9      116.2       89.8      104.2   

   Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10  \
0         May       June       July     August  September     October   
1        98.3      162.9      359.3      375.3      434.1       370.3   
2       239.8      270.7      245.2      241.5      272.5       352.5   
3       234.4        182      454.6      441.5      371.1       170.6   
4       131.9      321.8      549.1        634      396.6       208.5   
5       190.5      269.4      492.7      305.4      275.6       307.4   
6       204.4      128.1      174.7      169.9      208.3       436.1   
7       159.8        332      656.2      471.1      378.2       332.7   
8       270.2      488.9      617.5      685.2      651.5       370.4   
9        83.1      377.5        591      565.5      469.9       225.1   
10      250.9      597.1      633.1      573.4      591.8       358.3   
11       62.7      306.3      561.6      545.1      559.4       157.8   
12       56.8      143.2      234.6      325.3        203        78.3   
13       48.5      291.2      440.6      509.6      256.6       206.5   
14      973.1      965.6      918.5      924.9      868.9       618.6   
15     1168.6     1609.9     2362.8     1664.6       1222       948.3   
16      681.2      780.5      995.2      773.4      549.8       346.3   
17        743      861.1      976.7     1347.2      533.9       425.6   
18      503.1      889.2     1064.6      990.5      788.8       513.5   
19        293      477.6        586      624.9      483.2         391   

   Unnamed: 11 Unnamed: 12 Unnamed: 13  
0     November    December      ANNUAL  
1         50.7        77.6      1222.6  
2        383.8       198.7      1277.7  
3        164.1       259.7       6.812  
4        106.7        25.6      1119.9  
5        183.5        65.9      1409.5  
6        416.7       295.8      1365.3  
7          123        53.1      1544.9  
8         43.9       135.5      2102.9  
9        126.5       121.8      1606.3  
10       160.5        72.8      2099.8  
11       117.9        93.9      1433.7  
12        34.8        21.7       768.8  
13          42        61.6      1244.2  
14         583       617.5        2015  
15       231.4       127.6        2125  
16       126.9        41.1      3403.5  
17       230.7          72      4316.2  
18       132.1        56.5      3655.1  
19       152.3        61.3      1945.3

In [8]:
data2.info()
data2.dropna(how='any', inplace=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Unnamed: 0   24 non-null     object
 1   Unnamed: 1   25 non-null     object
 2   Unnamed: 2   25 non-null     object
 3   Unnamed: 3   25 non-null     object
 4   Unnamed: 4   25 non-null     object
 5   Unnamed: 5   25 non-null     object
 6   Unnamed: 6   25 non-null     object
 7   Unnamed: 7   25 non-null     object
 8   Unnamed: 8   25 non-null     object
 9   Unnamed: 9   25 non-null     object
 10  Unnamed: 10  25 non-null     object
 11  Unnamed: 11  25 non-null     object
 12  Unnamed: 12  25 non-null     object
 13  Unnamed: 13  25 non-null     object
dtypes: object(14)
memory usage: 2.9+ KB


In [9]:
data2.describe()

Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
count          24         24         24         24         24         24   
unique         24         24         24         24         24         24   
top        Punjab        105         96       87.5      113.2       98.3   
freq            1          1          1          1          1          1   

       Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11  \
count          24         24         24         24          24          24   
unique         24         24         24         24          24          24   
top         162.9      359.3      375.3      434.1       370.3        50.7   
freq            1          1          1          1           1           1   

       Unnamed: 12 Unnamed: 13  
count           24          24  
unique          24          24  
top           77.6      1222.6  
freq             1           1

In [10]:
print(data2.shape)

(24, 14)


In [11]:
print(data2['Unnamed: 0'].unique())

['Punjab' 'Royal Seema' 'Jammu & Kashmir' 'Saurashtra & Kutch'
 'South Karnatak' 'Tamil Nadu' 'Telangana' 'Uttarakhand' 'Vidharba'
 'West Bengal' 'West MP' 'West Rajasthan' 'West Up' 'Andaman & Nicobar'
 'Arunachal Pradesh' 'Assam & Megahlaya' 'Naga Mizo Mani'
 'SUB Himalaya WB & Sikkim' 'Orissa' 'Jharkhand' 'Bihar' 'East UP'
 'HARYANA DELHI & CHANDIGARH' 'HIMACHAL PRADESH']


In [12]:
y = data2["Unnamed: 13"]
y

1     1222.6
2     1277.7
3      6.812
4     1119.9
5     1409.5
6     1365.3
7     1544.9
8     2102.9
9     1606.3
10    2099.8
11    1433.7
12     768.8
13    1244.2
14      2015
15      2125
16    3403.5
17    4316.2
18    3655.1
19    1945.3
20    1898.6
21    1660.4
22    1545.5
23     986.7
24    1919.2
Name: Unnamed: 13, dtype: object

In [13]:
data2 = data2.drop('Unnamed: 0',axis=1)

In [14]:
x = data2.iloc[:,:1]
x

Unnamed: 1
1         105
2        79.5
3       367.8
4        12.5
5        24.4
6       141.2
7        98.7
8       173.1
9        74.9
10         60
11       54.1
12       21.4
13       68.6
14      276.9
15      164.5
16       83.9
17       91.4
18        103
19       70.9
20      102.9
21       81.2
22       56.2
23         61
24        211

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3, random_state = 1)

In [16]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
 
regressor = RandomForestRegressor(n_estimators = 100, random_state = 0)
regressor.fit(x,y) 

RandomForestRegressor(random_state=0)

In [17]:
model_rfc = RandomForestClassifier()
model_rfc.fit(x_train,y_train)

RandomForestClassifier()

In [18]:
train_acc = model_rfc.score(x_train,y_train)
print("The accuracy for train set is {}".format(train_acc*100))

The accuracy for train set is 100.0


In [19]:
y_pred = model_rfc.predict(x_test)

In [20]:
test_acc = accuracy_score(y_test,y_pred)
print("The accuracy for test set is {}".format(test_acc*100))

The accuracy for test set is 0.0


In [21]:
confusion_matrix = confusion_matrix(y_test,y_pred)
print(confusion_matrix) 

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
